#! /bin/sh
export RSYNC_PASSWORD='dragass'
rsync -av --delete --exclude */lost+found/* /home/troy/data hobgoblin.local::NetBackup/hammersmith
#rsync -av --delete --exclude */data/* /home/troy 192.168.1.51::NetBackup/hammersmith
  
