path=(~/.local/bin $path)
export PATH

HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000

setopt autocd
setopt HIST_SAVE_NO_DUPS

zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

bindkey -e
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search
bindkey "^[[3~" delete-char
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line

zstyle :compinstall filename '~/.zshrc'
zstyle ':completion:*' menu select
zstyle ':completion::complete:*' gain-privileges 1

autoload -Uz compinit up-line-or-beginning-search down-line-or-beginning-search
compinit

alias ls='ls --color=auto'
alias la='ls -al'
alias grep='grep --color=auto'

#ZSH_AUTOSUGGEST_STRATEGY=(completion)
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
#ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=243"
ZSH_AUTOSUGGEST_USE_ASYNC="true"

#source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh

if [ $commands[oc] ]; then
  source <(oc completion zsh)
  compdef _oc oc
fi

PROMPT='%(!.%F{red}.%F{magenta})%n%F{green}@%m %F{yellow}[%/]
%f%# '
